'use client'

import React from 'react'
import { ShineBorder } from '@/components/ui/shine-border'

const CardContainer = ({ children }) => (
  <div className="relative max-w-4xl mx-auto mt-4">
    <ShineBorder
      borderRadius={16}
      duration={8}
      color={['#9333EA', '#3B82F6']}
      className="w-full"
    >
      <div className="p-6">
        {children}
      </div>
    </ShineBorder>
  </div>
)

const BulletPoint = ({ emoji, title, content }) => (
  <div className="flex gap-2 items-start">
    <span className="text-purple-500 dark:text-purple-400 mt-1 text-xs">■</span>
    <div className="text-xs">
      <span className="font-bold text-purple-950 dark:text-purple-100">
        {title}
      </span>
      <span className="text-zinc-700 dark:text-zinc-300 ml-1">
        {content?.trim()}
      </span>
    </div>
  </div>
)

const SkillTag = ({ skill }) => (
  <span className="inline-flex items-center px-2 py-0.5 rounded-md text-xs font-medium bg-purple-100/80 text-purple-900 dark:bg-purple-900/30 dark:text-purple-100 border border-purple-200/50 dark:border-purple-500/30 shadow-sm">
    {skill}
  </span>
)

export function TldrCard({ data, children }) {
  if (children) {
    return <CardContainer>{children}</CardContainer>
  }

  if (!data) return null
  const { companyName, introText, bulletPoints, relevantSkills, title } = data

  return (
    <CardContainer>
      <div className="space-y-4">
        <div className="flex items-start justify-between">
          <h3 className="text-base font-bold text-purple-950 dark:text-purple-100 pr-8">
            {title || `✨ TL;DR - Why I'm a Great Fit for ${companyName || 'this role'}`}
          </h3>
          <div className="relative">
            <div className="text-sm text-purple-500 dark:text-purple-300 cursor-help hover:text-purple-600 dark:hover:text-purple-200 peer">?</div>
            <div className="absolute right-0 w-48 px-2 py-1 bg-white/90 dark:bg-zinc-800/90 backdrop-blur-sm rounded-lg shadow-xl text-xs text-zinc-600 dark:text-zinc-300 invisible peer-hover:visible opacity-0 peer-hover:opacity-100 transition-all duration-200 z-10">
              This content is generated by AI based on your job posting
            </div>
          </div>
        </div>

        <p className="text-xs text-purple-950/90 dark:text-purple-100/90">{introText}</p>

        <div className="space-y-2">
          {bulletPoints?.map((point, index) => {
            const match = point.match(/^\*\*([^*]+)\*\*\s*(.+)$/);
            if (!match) return null;
            const [, title, content] = match;
            return <BulletPoint key={index} title={title.trim()} content={content.trim()} />;
          })}
        </div>

        {relevantSkills?.length > 0 && (
          <div className="flex flex-wrap gap-1.5 pt-3 mt-3 border-t border-purple-200/30 dark:border-purple-500/30">
            {relevantSkills.map((skill, index) => (
              <SkillTag key={index} skill={skill} />
            ))}
          </div>
        )}
      </div>
    </CardContainer>
  )
} 